In [4]:
import numpy as np
import tensorflow as tf

g = tf.compat.v1.Graph()
with g.as_default():
    x = tf.compat.v1.placeholder(name='x', shape=[], dtype=tf.string)
    y = tf.compat.v1.placeholder(name='y', shape=[], dtype=tf.string)
    z = tf.strings.join([x, y], name='join', separator=' ')

with tf.compat.v1.Session(graph = g) as sess:
    result = sess.run(fetches=z, feed_dict={x:'hello', y:'world'})
    print(result)

b'hello world'


In [8]:
x = tf.Variable(0.0, name='x', dtype=tf.float32)
a = tf.constant(1.0)
b = tf.constant(-2.0)
c = tf.constant(1.0)

with tf.GradientTape() as tape:
    y = a * tf.pow(x, 2) + b * x + c

dy_dx = tape.gradient(y, x)
print(dy_dx)

tf.Tensor(-2.0, shape=(), dtype=float32)


In [11]:
@tf.function
def printbar():
    ts = tf.timestamp()
    today_ts = ts % (24 * 60 * 60)
    hour = tf.cast(today_ts // 3600 + 8, tf.int32) % tf.constant(24)
    minite = tf.cast((today_ts % 3600) // 60, tf.int32)
    second = tf.cast(tf.floor(today_ts % 60), tf.int32)

    def timeformat(m):
        if tf.strings.length(tf.strings.format('{}', m)) == 1:
            return tf.strings.format('0{}', m)
        return tf.strings.format('{}', m)
    
    timestring = tf.strings.join([timeformat(hour), timeformat(minite), timeformat(second)], separator=':')

    tf.print(timestring)

printbar()

22:53:36


In [12]:
tf.linspace(0.0, 6.28, 100)

<tf.Tensor: shape=(100,), dtype=float32, numpy=
array([0.        , 0.06343435, 0.1268687 , 0.19030304, 0.2537374 ,
       0.31717175, 0.38060609, 0.44404042, 0.5074748 , 0.57090914,
       0.6343435 , 0.6977778 , 0.76121217, 0.82464653, 0.88808084,
       0.9515152 , 1.0149496 , 1.0783839 , 1.1418183 , 1.2052526 ,
       1.268687  , 1.3321213 , 1.3955556 , 1.45899   , 1.5224243 ,
       1.5858587 , 1.6492931 , 1.7127274 , 1.7761617 , 1.839596  ,
       1.9030304 , 1.9664648 , 2.0298991 , 2.0933335 , 2.1567678 ,
       2.2202022 , 2.2836366 , 2.347071  , 2.4105053 , 2.4739397 ,
       2.537374  , 2.6008081 , 2.6642425 , 2.7276769 , 2.7911112 ,
       2.8545456 , 2.91798   , 2.9814143 , 3.0448487 , 3.108283  ,
       3.1717174 , 3.2351518 , 3.2985861 , 3.3620205 , 3.4254549 ,
       3.4888892 , 3.5523233 , 3.6157577 , 3.679192  , 3.7426264 ,
       3.8060608 , 3.8694952 , 3.9329295 , 3.9963639 , 4.0597982 ,
       4.1232324 , 4.186667  , 4.250101  , 4.3135357 , 4.37697   ,
       4.44040

In [13]:
tf.random.set_seed(3)
t = tf.random.uniform([5, 5], minval=0, maxval=10, dtype=tf.int32)
tf.print(t)

[[4 7 4 2 9]
 [9 1 2 4 7]
 [7 2 7 4 0]
 [9 6 9 7 2]
 [3 7 0 0 3]]


In [17]:
tf.print(t[2,4])
tf.print(t[0,0])

0
4


In [20]:
tf.print(tf.slice(t, [2, 2], [3, 2]))

[[7 4]
 [9 7]
 [0 0]]


In [21]:
a = tf.random.uniform(shape=[1,3,3,2], minval=0, maxval=255, dtype=tf.int32)
tf.print(a.shape)
tf.print(a)

TensorShape([1, 3, 3, 2])
[[[[162 113]
   [84 174]
   [230 17]]

  [[229 191]
   [37 36]
   [183 238]]

  [[45 208]
   [181 193]
   [211 195]]]]


In [22]:
b = tf.reshape(a, [3, 6])
tf.print(b)

[[162 113 84 174 230 17]
 [229 191 37 36 183 238]
 [45 208 181 193 211 195]]


In [23]:
a = tf.constant([[1.0,2.0],[3.0,4.0]])
b = tf.constant([[5.0,6.0],[7.0,8.0]])
c = tf.constant([[9.0,10.0],[11.0,12.0]])

In [25]:
d = tf.concat([a, b, c], axis=0)
tf.print(d.shape)
tf.print(d)

TensorShape([6, 2])
[[1 2]
 [3 4]
 [5 6]
 [7 8]
 [9 10]
 [11 12]]


In [27]:
e = tf.concat([a, b, c], axis=1)
tf.print(e.shape)
tf.print(e)

TensorShape([2, 6])
[[1 2 5 6 9 10]
 [3 4 7 8 11 12]]


In [28]:
f = tf.stack([a, b, c], axis=0)
tf.print(f.shape)
tf.print(f)

TensorShape([3, 2, 2])
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]

 [[9 10]
  [11 12]]]


In [29]:
g = tf.stack([a, b, c], axis=1)
tf.print(g.shape)
tf.print(g)

TensorShape([2, 3, 2])
[[[1 2]
  [5 6]
  [9 10]]

 [[3 4]
  [7 8]
  [11 12]]]


In [30]:
h = tf.stack([a, b, c], axis=2)
tf.print(h.shape)
tf.print(h)

TensorShape([2, 2, 3])
[[[1 5 9]
  [2 6 10]]

 [[3 7 11]
  [4 8 12]]]


In [35]:
a = tf.range(1, 10)
tf.print(a)
tf.print(tf.reduce_prod(a))

[1 2 3 ... 7 8 9]
362880


In [48]:
b = np.arange(1, 10)
print(b)
print(np.product(b))
print(1*2*3*4*5*6*7*8*9)

[1 2 3 4 5 6 7 8 9]
362880
362880


In [50]:
c = tf.constant([1, 2, 3])
d = tf.constant([[1], [2], [3]])
tf.print(c + d)

[[2 3 4]
 [3 4 5]
 [4 5 6]]


In [51]:
x = tf.Variable(1.0, dtype=tf.float32)

@tf.function
def add_x():
    x.assign_add(1.0)
    tf.print(x)
    return x

x1 = add_x()
x2 = add_x()
tf.print('*******' * 8)
tf.print(x1)
tf.print(x2)

2
3
********************************************************
2
3


In [52]:
@tf.function(autograph=True)
def myadd(a, b):
    for i in tf.range(3):
        tf.print(i)
    c = a + b
    print('tracing')
    return c

myadd(tf.constant('hello'), tf.constant('world'))
myadd(tf.constant('game'), tf.constant('designer'))
myadd(tf.constant(1), tf.constant(2))
myadd(tf.constant([3, 4]), tf.constant([5, 6]))
myadd(6, 7)
myadd(8, 9)

tracing
0
1
2
0
1
2
tracing
0
1
2
tracing
0
1
2
tracing
0
1
2
tracing
0
1
2


<tf.Tensor: shape=(), dtype=int32, numpy=17>

In [57]:
class DemoModule(tf.Module):
    def __init__(self, init_value = tf.constant(0.0), name = None):
        super(DemoModule, self).__init__(name = name)
        with self.name_scope:
            self.x = tf.Variable(init_value, dtype = tf.float32, trainable = True)
    
    @tf.function(input_signature = [tf.TensorSpec(shape=[], dtype=tf.float32)])
    def addprint(self, a):
        with self.name_scope:
            self.x.assign_add(a)
            tf.print(self.x)
            return self.x

demo = DemoModule(init_value = tf.constant(2.0))
res = demo.addprint(tf.constant(9.0))
print(res)
print(demo.submodules)

11
tf.Tensor(11.0, shape=(), dtype=float32)
()


In [59]:
tf.saved_model.save(demo, './data/demo/1', signatures = {'serving_default':demo.addprint})

Instructions for updating:
If using Keras pass *_constraint arguments to layers.
INFO:tensorflow:Assets written to: ./data/demo/1/assets
